%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\matlab\Documents\R\salary.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/19 17:21:26

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\matlab\Documents\R\Salary\salary.xlsx','Sheet1','A1:C28','',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
raw = raw(:,[2,3]);
dates = dates(:,1);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
PayDate = datetime([dates{2:end,1}].', 'ConvertFrom', 'Excel', 'Format', 'MM/dd/yyyy');
BeforeTax = data(2:end,1);
AfterTax = data(2:end,2);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% PayDate=datenum(PayDate);

%% Calculate Taxes

Money = zeros(27,3);
Money(:,1)= BeforeTax(1:end);
Money(:,2)= AfterTax(1:end);





%% Clear temporary variables
clearvars data raw dates R;